"use client";
import Link from "next/link";import { useEffect,useMemo,useState } from "react";import { dateKey,moods,MoodOption,timeText } from "../lib/moods";
type Note={id:number;date:string;content:string;recordedAt:string;timeUnknown:boolean;mood:string;moodLabel:string;moodIcon:string;moodScore:number};type Profile={nickname:string;avatar:string};const avatars=["🌤️","☀️","🌻","🌙","🌈","🍀","🐱","🐰"];
export default function Record(){const today=useMemo(()=>dateKey(new Date()),[]),[targetDate,setTargetDate]=useState(today),[time,setTime]=useState(""),[content,setContent]=useState(""),[selected,setSelected]=useState<MoodOption|null>(null),[notes,setNotes]=useState<Note[]>([]),[status,setStatus]=useState("idle"),[profile,setProfile]=useState<Profile|null|undefined>(undefined),[nickname,setNickname]=useState(""),[avatar,setAvatar]=useState("🌤️");
useEffect(()=>{const q=new URLSearchParams(window.location.search).get("date");if(q&&/^\d{4}-\d{2}-\d{2}$/.test(q))setTargetDate(q);if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js");Promise.all([fetch("/api/profile").then(r=>r.json()),fetch("/api/moods").then(r=>r.json())]).then(([p,d])=>{setProfile(p.profile);setNotes(d.notes??[])})},[]);
async function register(){const r=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nickname,avatar})});if(r.ok)window.location.reload()}
async function save(){if(!content.trim())return;setStatus("saving");const recordedAt=time?new Date(`${targetDate}T${time}:00`).toISOString():undefined,r=await fetch("/api/moods",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date:targetDate,content,recordedAt,timeUnknown:!time,mood:selected?.id,moodLabel:selected?.label,moodIcon:selected?.icon,moodScore:selected?.score})});if(r.ok){const d=await r.json();setNotes(v=>[...v,d.note]);setContent("");setTime("");setSelected(null);setStatus("saved");setTimeout(()=>setStatus("idle"),1400)}else setStatus("error")}
if(profile===undefined)return <main className="onboarding"><div className="brand"><span className="brand-sun">☀</span>晴天</div><p>正在准备你的晴天…</p></main>;
if(!profile)return <main className="onboarding"><div className="onboarding-card"><span className="welcome-sun">☀</span><h1>欢迎来到晴天</h1><p>先给自己的心情空间起个名字吧。</p><div className="avatar-picker">{avatars.map(a=><button key={a} className={avatar===a?"selected":""} onClick={()=>setAvatar(a)}>{a}</button>)}</div><input value={nickname} maxLength={16} onChange={e=>setNickname(e.target.value)} placeholder="你的昵称"/><button className="start-button" onClick={register} disabled={!nickname.trim()}>开始记录</button><small>无需手机号或账号，资料只属于这台设备。</small></div></main>;
const dayNotes=notes.filter(n=>n.date===targetDate),display=new Date(`${targetDate}T12:00:00`),isToday=targetDate===today;return <main className="app-shell"><header className="app-header"><div className="profile-mini"><span>{profile.avatar}</span><div><small>你好</small><strong>{profile.nickname}</strong></div></div><Link href={`/day/${targetDate}`} className="header-link">这一天的记录 →</Link></header><section className="composer-page"><div className="date-pill">{isToday?"今天":`${display.getMonth()+1}月${display.getDate()}日`} · {display.toLocaleDateString("zh-CN",{weekday:"long"})}</div><h1>{isToday?"记下这一刻":"补记那一天"}</h1><p className="hero-copy">时间和心情都可以留空，系统会标记为未知。</p><div className="composer-card"><div className="record-datetime"><label>日期<input type="date" value={targetDate} max={today} onChange={e=>setTargetDate(e.target.value)}/></label><label>时间（可不选）<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><textarea autoFocus value={content} onChange={e=>setContent(e.target.value)} maxLength={500} placeholder="发生了什么？那一刻有什么感受……"/><div className="note-mood-title">这条随笔的心情（可不选）</div><div className="quick-moods">{moods.slice(0,10).map(m=><button key={m.id} className={selected?.id===m.id?"selected":""} onClick={()=>setSelected(selected?.id===m.id?null:m)}><span>{m.icon}</span><small>{m.label}</small></button>)}</div><div className="unknown-hints"><span>{time?`🕐 ${time}`:"❔ 时间未知"}</span><span>{selected?`${selected.icon} ${selected.label}`:"❔ 心情未知"}</span></div><div className="composer-footer"><span>{content.length}/500</span><button onClick={save} disabled={!content.trim()||status==="saving"}>{status==="saving"?"保存中…":status==="saved"?"已记下 ✓":"保存随笔"}</button></div>{status==="error"&&<p className="error">保存失败，请稍后重试。</p>}</div>{dayNotes.length>0&&<div className="today-preview"><div><strong>这一天已记录 {dayNotes.length} 次</strong><Link href={`/day/${targetDate}`}>查看全部</Link></div>{dayNotes.slice(-2).reverse().map(n=><article key={n.id}><span>{n.moodIcon}</span><p>{n.content}</p><time>{n.timeUnknown?"时间未知":timeText(n.recordedAt)}</time></article>)}</div>}</section></main>}
